language: node_js
node_js:
  - '10'
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: npm
  email: sh@signalwerk.ch
  api_key:
    secure: GdyeN/MSH7Xj4WWAtgB0h/7tfryUMHmZEd8tqQgiFqMp1LigdlyIMRuQrF4VBew5uChNboz5kcsgKBhXrTa1IlJVyKcuBAUsDE/K510i+wcCbqzotlqZFO36c/1xv1RdO3LaLI4w5AcwtXRw2EoaOQ5sauxCwTs7cbqCe1WIo64o8SbOprnNmur9wQVlbHNTboa8gfVfb2OYTVKEeSqAHIFfXSrlsaZdGFg2vmmpSwqqm+ggrCTuuASvAeInRT5I1jVRLd5HAqkA25L8xTnJSWh9KH6MRDGUqeNWMgKGkt/P4xIS7+A11+6gG1gWS7b80izoMqzIbloYoa/NFyziV9IIQetXcxPjYNS8+AIobHE5ZsaJJLO21ju3c5KhxNoBjUryqnJmSnBYJYxuV7QjILczLjCoKgT+Nl3Esog3X3AsTDkQFs6frRtI46sTD3HSzgDqfRELHi5XuKGyELnqNwt3mjVu8IDn0yywhBAo6ZegUI+NQv/x2PkjroiJqNtv4VemUIuPqHKoxoCAoazRQBLz4hCqoyPThKEnPjc68HxQjs8BrylJ/HxaY2wjQwwl9A+l9ejhwnHNxrIDXaO1wF5GN/+Lc8MsYybCk+W2E15576P6c3eMTKFnYVm2vlK/zLv6J2BIrabENdvUolVV7NErA5hU4AY2wZate521KJA=
  on:
    branch: beta
    tags: true
branches:
  only:
  - master
  - beta
